Migrate raster to terra, restructuring and reformatting
GeoScripting-WUR/Scripting4GeoIntro pull request #18
Opened 2022-11-24 10:00 UTC by mvansluijs

2022-11-27 12:08 UTC, GreatEmerald requested changes
Thanks! A few minor changes suggested.

Apparently I don't get notifications about these anywhere, even in GitHub notification centre, so I think you need to assign me (or if you can't do that, put @GreatEmerald in the pull request text) for me to get notified.

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +In future tutorials we will show you how you can read and write different spatial objects (e.g. vector and raster files).
Technically this should be "later" or "subsequent", otherwise can be interpreted as tutorials that have not been developed yet

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +if(!"terra" %in% rownames(installed.packages())){install.packages("terra")}
Something I recently found out: in this command you can leave out the `rownames()` and it will still work! I'm not entirely sure how, but `rownames()` are implied here. This would make it a bit more simple and memorable.

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +# converted to the raster package file format
`terra`?

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +        plot(z, 1) # Plots the first layer of the resulting SpatRaster
Does this actually work? Typically `plot()` commands in functions are ignored unless you explicitly wrap them in `print()`.

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +# Create a raster layer and fill it with "randomly" generated integer values
`SpatRaster`?

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +# Now, b and a are raster layers, and c is ''corrupted''
`SpatRaster`s?

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +  download.file(url = data_URL, destfile = 'data/data.zip', method = 'auto', mode = 'wb')
Are the `method` and `mode` actually necessary? They certainly are not under Linux.

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +We load the administrative boundaries of the Philippines, using the `sf` library, to which you will be introduced more in-depth in a future tutorial:
`sf` package?

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +# Check for the terra package and install if missing
`sf` rather than `terra`

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +if(!"sf" %in% rownames(installed.packages())){install.packages("sf")}
ditto

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +  download.file(url = data_URL, destfile = 'data/data.zip', method = 'auto', mode = 'wb')
Also, if you are using `data_folder`, then this should be: `destfile = file.path(data_folder, "data.zip")`

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +adm <- st_read(paste0(data_folder, "/gadm41_PHL_2.json"), quiet = TRUE)
`file.path` is a more elegant solution compared to `paste0` and using a `/`

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +data_folder <- "data"
Note that they are called "folders" only in Windows. On Linux they are called "directories". So perhaps `data_dir` would be a more cross-platform name.

2022-11-27 12:08 UTC, GreatEmerald commented on index.Rmd
> +               labels = as.character(adm$NAME_2[adm$NAME_1 == "Marinduque"]), cex = 1.1, col = "white", font = 2))
Why use `adm` instead of `mar` here?

2022-11-28 10:04 UTC, mvansluijs commented on index.Rmd
> +        plot(z, 1) # Plots the first layer of the resulting SpatRaster
Yes, this does work!

2022-11-28 10:06 UTC, mvansluijs commented on index.Rmd
> +  download.file(url = data_URL, destfile = 'data/data.zip', method = 'auto', mode = 'wb')
`method` and `mode` were necessary at some point (or in another tutorial), otherwise Windows threw errors, either when downloading or when unzipping. It seems to not cause any issues now when I remove them here, so I did remove them in this case. I'll check where else they are superfluous.

2022-11-28 10:11 UTC, mvansluijs commented on index.Rmd
> +               labels = as.character(adm$NAME_2[adm$NAME_1 == "Marinduque"]), cex = 1.1, col = "white", font = 2))
`mar` no longer has the `NAME_` attributes, as it is only the geometry subset (comes from `adm_geom`). As a result we need to use `adm` here. Given this context and your confustion, I'm not sure if the current solution is the most elegant actually.

2022-11-28 10:15 UTC, mvansluijs commented
@GreatEmerald weird that you don't get notified. At least that will probably also mean that we are not bothering anyone else who is part of [Geoscripting @ Wageningen University](https://github.com/GeoScripting-WUR) with pull requests. I'll make sure to @ you in the other pull requests. I've implemented most suggested changes for this one. To some of your comments I replied. Do you get notified of those replies? If not, I'll also @ you there.

2022-11-28 18:13 UTC, GreatEmerald commented on index.Rmd
> +               labels = as.character(adm$NAME_2[adm$NAME_1 == "Marinduque"]), cex = 1.1, col = "white", font = 2))
Well, you can keep the whole data.frame rather than just the geometry, and use `st_geometry()` whenever it's necessary.

2022-11-28 18:15 UTC, GreatEmerald commented
Yes, I get notified about replies! And thanks for the changes, it looks good overall. If you come up with something simpler for the plotting, feel free to make a new pull request.

2022-11-28 18:15 UTC, GreatEmerald approved these changes

2022-11-28 18:16 UTC, merged